name: Regenerate bird

on:
  watch:
    types: [started]

concurrency: 
  group: "PoemaIX-BIRDGen"
  cancel-in-progress: true

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    env:
      GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa"
    steps:
    - name: Checkout Central Actions Repo
      uses: actions/checkout@v3
    - name: symlink to /root/arouteserver
      run: |
        sudo chmod 777 /root
        ln -s $GITHUB_WORKSPACE /root/arouteserver
    - name: setup ssh key
      run: |
        sudo chmod 777 /root
        mkdir -p /root/.ssh
        sudo chown "$USER" /root/.ssh
        echo "$SSH_KEY_IXPAGE" > /root/.ssh/id_rsa_ixpage
        chmod 600  /root/.ssh/id_rsa_ixpage
        echo "$SSH_KEY_ARS" > /root/.ssh/id_rsa_ars
        chmod 600  /root/.ssh/id_rsa_ars
        echo "$IXLAN_OVPN_CONF" > /root/.ssh/ovpn-kskb-ix.conf
        git config --global user.email si@kskb.eu.org
        git config --global user.name KusakabeSi
        echo $HOME
        echo $GITHUB_WORKSPACE
      shell: bash
      env:
        SSH_KEY_IXPAGE: ${{secrets.SSH_KEY_IXPAGE}}
        SSH_KEY_ARS: ${{secrets.SSH_KEY_ARS}}
        IXLAN_OVPN_CONF: ${{secrets.IXLAN_OVPN_CONF}}
    - name: Install depends
      run: sudo apt-get install -y bgpq4 openvpn net-tools
    - name: connect to openvpn
      run: |
        sudo openvpn --daemon --config /root/.ssh/ovpn-kskb-ix.conf
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
      
    - name: Cache /root/gitrs/KSKB-IX files
      id: cache_ix_page
      uses: actions/cache@v2
      with:
        path: |
          /root/gitrs/KSKB-IX
        key: I am a key for /root/gitrs/KSKB-IX at PoemaIX-BIRDGen v2!
    - name: Sync from /root/gitrs/KSKB-IX
      if: steps.cache_ix_page.outputs.cache-hit != 'true'
      run: |
        git clone git@github.com:KSKBpage/KSKB-IX.git /root/gitrs/KSKB-IX
      env:
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa_ixpage"
    - name: reset to KSKB-IX origin
      run: |
        cd  /root/gitrs/KSKB-IX
        git fetch --all --force
        git reset --hard origin/main
      env:
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa_ixpage"
        
    - name: Cache /root/gitrs/ars files
      id: cache_ars
      uses: actions/cache@v2
      with:
        path: |
          /root/gitrs/ars
        key: I am a key for /root/gitrs/ars at PoemaIX-BIRDGen v2!
    - name: Sync from /root/gitrs/ars
      if: steps.cache_ars.outputs.cache-hit != 'true'
      run: |
        git clone git@github.com:KusakabeShi/arouteserver.git /root/gitrs/ars
      env:
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa_ars"
    - name: reset to ars origin
      run: |
        cd  /root/gitrs/ars
        git fetch --all --force
        git reset --hard origin/KSKB-IX
      env:
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa_ars"
        
    - name: regenerate bird config and ix-f.json
      run: |
        sudo pip3 install -r /root/gitrs/ars/requirements.txt
        /root/arouteserver/updatears.sh
      env:
        SECRET_PEERINGDB_API_KEY: ${{secrets.SECRET_PEERINGDB_API_KEY}}
        HOME: /root
      shell: bash
      
    - name: push ixpage back
      run: |
        git config --global user.email si@kskb.eu.org
        git config --global user.name KusakabeSi
        /root/arouteserver/sync_ixpage.sh
      env:
        HOME: /root
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa_ixpage"
      shell: bash
    - name: push ars back
      run: |
        cd  /root/gitrs/ars
        git add -A
        git diff-index --quiet HEAD || git commit -m "update"
        git push
      env:
        HOME: /root
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa_ars"
      shell: bash
    - name: Commit #upload new refresh_token
      run: |
        cd $GITHUB_WORKSPACE
        git add -A
        git diff-index --quiet HEAD || git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
